# Generated by Django 5.2.7 on 2025-10-14 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=False, verbose_name='Grafo activo')),
            ],
            options={
                'verbose_name': 'Grafo',
                'verbose_name_plural': 'Grafos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_source', models.BooleanField(default=False, verbose_name='Es nodo origen')),
                ('x_position', models.FloatField(blank=True, null=True, verbose_name='Posición X')),
                ('y_position', models.FloatField(blank=True, null=True, verbose_name='Posición Y')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.graph', verbose_name='Grafo')),
            ],
            options={
                'verbose_name': 'Nodo',
                'verbose_name_plural': 'Nodos',
                'ordering': ['name'],
                'unique_together': {('graph', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, verbose_name='Peso')),
                ('directed', models.BooleanField(default=True, verbose_name='Dirigida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='core.graph', verbose_name='Grafo')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='core.node', verbose_name='Nodo origen')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='core.node', verbose_name='Nodo destino')),
            ],
            options={
                'verbose_name': 'Arista',
                'verbose_name_plural': 'Aristas',
                'ordering': ['from_node__name', 'to_node__name'],
                'unique_together': {('graph', 'from_node', 'to_node')},
            },
        ),
    ]
